"""Module with variables large"""

# List of strings with possibles garbage found in files txt that were extracted of pdf with pdfbox
from typing import List

list_str_garbage: List[str] = [
    '\n',
    '\r',
    '"',
    '}',
    '{',
    '_',
    '',
    '',
    '',
    'Page 1 of 1',
    'Page 1 of 2',
    'Page 1 of 3',
    'Page 1 of 4',
    'Page 1 of 5',
    'Page 1 of 6',
    'Page 1 of 7',
    'Page 2 of 2',
    'Page 2 of 3',
    'Page 2 of 4',
    'Page 2 of 5',
    'Page 2 of 6',
    'Page 2 of 7',
    'Page 2 of 2',
    'Page 3 of 3',
    'Page 3 of 4',
    'Page 3 of 5',
    'Page 3 of 6',
    'Page 3 of 7',
    'Page 4 of 4',
    'Page 4 of 5',
    'Page 4 of 6',
    'Page 4 of 7',
    'Page 5 of 5',
    'Page 5 of 6',
    'Page 5 of 7',
    'Page 6 of 6',
    'Page 6 of 7',
    'Page 7 of 7',
    '  ',
    '   ',
    '    ',
    '     ',
    '      ',
    '       ',
    '        ',
    '         ',
    '          ',
    '           ',
    '            ',
    '             ',
    '              ',
    '               ',
    '                ',
    '                 ',
    '                  ',
    '                   ',
    '                    ',
    '                     ',
    '                      ',
    '                       ',
    '                        ',
    '                         ',
    '                          ',
    '                           ',
    '                            ',
    '                             ',
    '                              ',
    '                               ',
    '                                ',
    '                                 ',
    '                                  ',
    '                                   ',
    '                                    ',
    '                                     ',
    '                                      ',
    '                                       ',
    '                                        ',
    '                                         ',
    '                                          ',
    '                                           ',
    '                                            ',
    '                                             ',
    '                                              ',
    '                                               ',
    '                                                ',
    '                                                 ',
    '                                                  ',
    '                                                   ',
    '                                                    ',
    '                                                     ',
    '                                                      ',
    '                                                       ',
    '                                                        ',
    '                                                         ',
    '                                                          ',
    '                                                           ',
    '                                                            ',
    '                                                             ',
    '                                                              ',
    '                                                               ',
    '                                                                ',
    '                                                                 ',
    '                                                                  ',
    '                                                                   ',
    '                                                                    ',
    '                                                                     ',
    '                                                                      ',
    '                                                                       ',
]
